name: lookout
description: An app that lets you plan your social media looks.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  go_router: ^6.0.1
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  apptheme:
    path: packages/apptheme

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
   - assets/HomePage/sc.png
   - assets/SocialMediaLogo/
